/** @type {import('tailwindcss').Config} */
// Tokens portados fielmente do design system "Butterfly Wellness" (Google Stitch / Material 3).
// Paleta: Primária Emerald Mint (crescimento), Secundária Soft Lavender (mente/mindfulness),
// Neutros warm-gray (sem pretos puros). Tipografia dual: Plus Jakarta Sans + Work Sans.
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        surface: '#fbf9f8',
        'surface-dim': '#dbd9d9',
        'surface-bright': '#fbf9f8',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f5f3f3',
        'surface-container': '#efeded',
        'surface-container-high': '#eae8e7',
        'surface-container-highest': '#e4e2e2',
        'on-surface': '#1b1c1c',
        'on-surface-variant': '#3d4a41',
        'inverse-surface': '#303030',
        'inverse-on-surface': '#f2f0f0',
        outline: '#6d7a71',
        'outline-variant': '#bccabf',
        'surface-tint': '#006c46',
        primary: '#006c46',
        'on-primary': '#ffffff',
        'primary-container': '#2eb67d',
        'on-primary-container': '#004128',
        'inverse-primary': '#5edda0',
        secondary: '#645785',
        'on-secondary': '#ffffff',
        'secondary-container': '#d9caff',
        'on-secondary-container': '#5f5380',
        tertiary: '#55615e',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#97a4a0',
        'on-tertiary-container': '#2e3a38',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#7cfabb',
        'primary-fixed-dim': '#5edda0',
        'on-primary-fixed': '#002112',
        'on-primary-fixed-variant': '#005234',
        'secondary-fixed': '#e9ddff',
        'secondary-fixed-dim': '#cebff3',
        'on-secondary-fixed': '#1f143e',
        'on-secondary-fixed-variant': '#4c406c',
        'tertiary-fixed': '#d8e5e1',
        'tertiary-fixed-dim': '#bcc9c6',
        'on-tertiary-fixed': '#121e1c',
        'on-tertiary-fixed-variant': '#3d4947',
        background: '#fbf9f8',
        'on-background': '#1b1c1c',
        'surface-variant': '#e4e2e2',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
      spacing: {
        lg: '48px',
        'container-padding': '20px',
        md: '24px',
        base: '8px',
        sm: '12px',
        xs: '4px',
        gutter: '16px',
      },
      fontFamily: {
        'body-md': ['Work Sans', 'system-ui', 'sans-serif'],
        'body-sm': ['Work Sans', 'system-ui', 'sans-serif'],
        'body-lg': ['Work Sans', 'system-ui', 'sans-serif'],
        'headline-xl': ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        'headline-lg': ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        'headline-md': ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        'label-md': ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        'headline-lg-mobile': ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-xl': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '20px', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '600' }],
      },
      boxShadow: {
        // "butterfly-light": high-diffusion, low-opacity com leve tint lavanda
        ambient: '0 4px 24px -1px rgba(100, 87, 133, 0.08)',
        'ambient-lg': '0 12px 40px -4px rgba(100, 87, 133, 0.12)',
      },
      keyframes: {
        'fade-in': {
          '0%': { opacity: '0', transform: 'translateY(8px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'flutter': {
          '0%, 100%': { transform: 'translateY(0) rotate(-2deg)' },
          '50%': { transform: 'translateY(-6px) rotate(2deg)' },
        },
        'pop': {
          '0%': { transform: 'scale(0.9)', opacity: '0' },
          '60%': { transform: 'scale(1.04)' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
      },
      animation: {
        'fade-in': 'fade-in 0.4s ease-out both',
        flutter: 'flutter 4s ease-in-out infinite',
        pop: 'pop 0.35s ease-out both',
      },
    },
  },
  plugins: [],
}
