-- ============================================================================
-- App Butterfly — Migration 0004
-- Adiciona o TEXTO completo de cada aula (coluna content) e o VIDEO (video_url).
-- Os videos sao referencias externas do YouTube (conteudo inicial/placeholder,
-- para trocar futuramente pelas gravacoes oficiais do metodo).
-- Rode no SQL Editor DEPOIS da 0003.
-- ============================================================================

alter table public.lessons add column if not exists content text;

update public.lessons as l
set content = v.content, video_url = v.video
from (values

-- ===== Modulo: Alinhamento de Mentalidade =====
('men-01', E'A metamorfose comeca muito antes do prato: comeca na forma como voce pensa sobre si mesma e sobre comida.\n\nNesta aula voce vai entender por que a mentalidade responde pela maior parte do resultado. Dietas baseadas so em regras falham porque ignoram as crencas que sustentam os habitos. Quando a mente muda, as escolhas mudam sozinhas.\n\nPratica de hoje: escreva em uma frase quem voce quer se tornar nos proximos 45 dias. Leia essa frase toda manha.', 'https://www.youtube.com/watch?v=nsr41Byz3RY'),
('men-02', E'A autossabotagem nao e falta de forca de vontade: e um padrao automatico de protecao. Entender o gatilho e o primeiro passo para desarma-lo.\n\nMapeie as situacoes em que voce costuma sair do plano (cansaco, ansiedade, festas, brigas). Para cada gatilho, crie de antemao uma resposta nova e simples. O objetivo nao e ser perfeita, e ter um plano B pronto.\n\nPratica: liste seus 3 principais gatilhos e uma acao substituta para cada um.', 'https://www.youtube.com/watch?v=IaVvM0JEBHw'),
('men-03', E'A dieta punitiva funciona na base da culpa, e a culpa cansa. O metodo Butterfly troca punicao por escolha consciente.\n\nCada refeicao e uma decisao, nao um julgamento moral. Comer algo fora do plano nao faz de voce um fracasso; e apenas um dado. A leveza vem quando voce para de se punir e volta a se cuidar na proxima escolha.\n\nPratica: troque a frase "eu nao posso" por "eu escolho" durante um dia inteiro e observe a diferenca.', 'https://www.youtube.com/watch?v=KJetV1O4PIY'),
('men-04', E'Habitos sustentaveis nascem pequenos. Grandes viradas costumam durar pouco; micro-habitos se mantem.\n\nUse a tecnica do empilhamento: ancore um habito novo em algo que voce ja faz. Exemplo: "depois de escovar os dentes, bebo um copo de agua". A repeticao cria o automatismo, e o automatismo libera sua energia para o que importa.\n\nPratica: escolha 1 micro-habito e empilhe-o em uma rotina que ja existe no seu dia.', 'https://www.youtube.com/watch?v=DzIeFgIcz_I'),
('men-05', E'Toda transformacao precisa de um destino. Sua visao de borboleta e a imagem clara de quem voce sera ao fim dos 45 dias.\n\nQuanto mais viva a imagem (como voce se sente, veste, dorme, se move), mais forte a ancora nos momentos dificeis. Nao e sobre um numero na balanca, e sobre uma versao mais leve de voce.\n\nPratica: descreva em 5 linhas o seu "eu borboleta" e releia sempre que bater a vontade de desistir.', 'https://www.youtube.com/watch?v=-BWiiY2S6R4'),

-- ===== Guia de Alimentos (nutricao) =====
('nut-01', E'Os macronutrientes (proteinas, gorduras e carboidratos) conversam com o seu corpo o tempo todo. Entender essa conversa e a base de tudo.\n\nProteinas constroem e saciam; gorduras boas regulam hormonios; carboidratos dao energia, mas em excesso e na forma errada inflamam. Na Fase 1, o foco e reduzir os carboidratos refinados e priorizar comida de verdade.\n\nPratica: em cada refeicao de hoje, garanta uma fonte de proteina e uma de gordura boa.', 'https://www.youtube.com/watch?v=80iqjwD0btc'),
('nut-02', E'Superalimentos nao precisam ser caros nem exoticos. Sao alimentos densos em nutrientes que cabem no seu dia a dia.\n\nFolhas verde-escuras, frutas vermelhas, castanhas, sementes, ovos e peixes pequenos entregam muito por porcao. O segredo nao e comer de tudo, e comer bem daquilo que nutre.\n\nPratica: inclua 2 superalimentos em uma refeicao de hoje (ex: espinafre e castanhas).', 'https://www.youtube.com/watch?v=L0DTHT1UBJg'),
('nut-03', E'O prato anti-inflamatorio segue uma regra simples e visual: metade de vegetais, um quarto de proteina, um quarto de gordura boa ou carboidrato do bem.\n\nEssa proporcao estabiliza a glicose, prolonga a saciedade e reduz a inflamacao. Voce nao precisa contar calorias, precisa montar bem o prato.\n\nPratica: monte seu almoco seguindo a regra do prato e observe como voce se sente 2 horas depois.', 'https://www.youtube.com/watch?v=KpUnMbkDLfU'),
('nut-04', E'O acucar refinado e um dos maiores gatilhos inflamatorios, e ele se esconde onde voce menos espera: molhos, paes, bebidas e produtos "fit".\n\nAprenda a reconhecer os nomes disfarcados (xarope de milho, maltodextrina, dextrose). Reduzir acucar nao e sofrimento: e recuperar o paladar para o sabor real dos alimentos.\n\nPratica: leia o rotulo de 3 produtos da sua despensa e procure o acucar escondido.', 'https://www.youtube.com/watch?v=PBiL9_S2g9k'),
('nut-05', E'Gordura nao e vila. A gordura certa emagrece, sacia e regula hormonios.\n\nPrefira azeite de oliva, abacate, castanhas e o omega-3 dos peixes. Evite gorduras trans e oleos vegetais refinados usados em frituras e ultraprocessados. A diferenca entre uma gordura e outra muda todo o resultado.\n\nPratica: troque um oleo refinado por azeite ou oleo de coco em um preparo de hoje.', 'https://www.youtube.com/watch?v=Ha2c90GoAIk'),
('nut-06', E'A agua e a ferramenta mais barata e subestimada do protocolo. A meta e cerca de 35ml por kg de peso (perto de 2L).\n\nA hidratacao ajuda a eliminar toxinas, reduz a retencao e diminui a falsa fome. Muitas vezes o corpo pede agua e a gente interpreta como vontade de comer.\n\nPratica: comece o dia com um copo de agua e registre a agua no seu Check-in Diario.', 'https://www.youtube.com/watch?v=s0P2_XJXGF8'),
('nut-07', E'Saber ler rotulos e um superpoder. Em 10 segundos voce decide se um produto entra ou nao no carrinho.\n\nRegra pratica: olhe a lista de ingredientes (nao so a tabela nutricional). Quanto menor a lista e mais reconheciveis os nomes, melhor. Fuja de listas longas cheias de palavras quimicas e acucares.\n\nPratica: escolha o produto com a lista de ingredientes mais curta na sua proxima compra.', 'https://www.youtube.com/watch?v=QgNvPV08_gA'),
('nut-08', E'Seu intestino e seu segundo cerebro. Uma microbiota saudavel melhora humor, imunidade e a forma como voce absorve nutrientes.\n\nFibras (vegetais, sementes) e alimentos fermentados alimentam as bacterias boas. Um intestino inflamado sabota o emagrecimento e a energia.\n\nPratica: inclua uma fonte de fibra em cada refeicao de hoje e observe a digestao.', 'https://www.youtube.com/watch?v=VRFKOtWkNCA'),
('nut-09', E'Comer fora nao precisa sabotar o plano. Com estrategia, voce mantem a linha em restaurantes, festas e viagens.\n\nDefina o prato antes de sentir fome, comece pela salada e pela proteina, beba agua e evite o "modo automatico" do bufe. Uma escolha consciente vale mais que a perfeicao impossivel.\n\nPratica: no proximo evento, decida o que vai comer antes de chegar.', 'https://www.youtube.com/watch?v=mWGGdEQH-LM'),
('nut-10', E'A batalha do emagrecimento se ganha no mercado, nao na cozinha. O que voce nao compra, nao come.\n\nMonte uma lista organizada por secao, va ao mercado sem fome e priorize a periferia do supermercado (hortifruti, acougue), onde estao os alimentos de verdade.\n\nPratica: monte sua lista Butterfly da semana antes de sair de casa.', 'https://www.youtube.com/watch?v=80iqjwD0btc'),
('nut-11', E'O jejum intermitente pode ajudar a desinflamar e organizar as janelas alimentares, mas nao e para todo mundo.\n\nComece simples (ex: 12 horas sem comer, incluindo o sono) e evolua com seguranca. Pessoas com condicoes clinicas devem falar com o profissional parceiro antes.\n\nPratica: experimente encerrar o jantar mais cedo e observar a fome da manha seguinte.', 'https://www.youtube.com/watch?v=Wxe2oKgHlrE'),
('nut-12', E'Planejar o cardapio da semana e o que separa quem segue o plano de quem cai na tentacao.\n\nEscolha 3 cafes, 3 almocos e 3 jantares que voce gosta e repita. Simplicidade gera consistencia. Deixe opcoes prontas para os dias corridos.\n\nPratica: defina o cardapio dos proximos 3 dias e faca a lista de compras correspondente.', 'https://www.youtube.com/watch?v=xjERtIVH7VY'),

-- ===== Receitas Butterfly (recipe) =====
('rec-01', E'O cafe da manha certo estabiliza sua energia e reduz a fome do resto do dia.\n\nAposte em proteina e gordura boa: ovos, abacate, iogurte natural, castanhas. Evite comecar o dia so com carboidrato, que gera pico e queda de glicose.\n\nExperimente: ovos mexidos com folhas e azeite, ou iogurte natural com frutas vermelhas e sementes.', 'https://www.youtube.com/watch?v=_0oVPpvMZTY'),
('rec-02', E'Almocos de baixa friccao sao completos e faceis de digerir, para voce nao apagar no meio da tarde.\n\nUse a regra do prato: vegetais, uma boa proteina e uma gordura boa. Tempere com ervas, alho e azeite.\n\nExperimente: file de frango grelhado, salada colorida e abobrinha refogada no azeite.', 'https://www.youtube.com/watch?v=NkdTJpY6MyY'),
('rec-03', E'Jantares leves e quentes acalmam o corpo e preparam para um sono melhor.\n\nSopas, refogados e assados de vegetais com proteina sao perfeitos. Evite refeicoes muito pesadas ou cheias de carboidrato refinado a noite.\n\nExperimente: creme de abobora com gengibre e um ovo pochet por cima.', 'https://www.youtube.com/watch?v=iYwrcMsVHKg'),
('rec-04', E'O lanche da tarde e onde muita gente escorrega. Ter opcoes prontas evita o ataque ao acucar.\n\nCastanhas, fruta com pasta de amendoim sem acucar, iogurte natural ou ovos cozidos resolvem a fome das 16h.\n\nExperimente: um punhado de castanhas com uma fruta vermelha.', 'https://www.youtube.com/watch?v=aOCap7ELDNs'),
('rec-05', E'Da para ter pao e massa no protocolo, desde que nas versoes certas, sem trigo refinado.\n\nPao de farinha de amendoas, tapioca fina e macarrao de vegetais (abobrinha, palmito) sao otimas escolhas.\n\nExperimente: uma tapioca fina com recheio de ovo e folhas.', 'https://www.youtube.com/watch?v=igrjfAb7hl8'),
('rec-06', E'Uma boa salada sustenta e nao pesa. O segredo e a variedade e uma boa gordura.\n\nCombine folhas, legumes coloridos, uma proteina e finalize com azeite e sementes. Salada nao precisa ser sinonimo de fome.\n\nExperimente: folhas, grao-de-bico, tomate, pepino, azeite e gergelim.', 'https://www.youtube.com/watch?v=NkdTJpY6MyY'),
('rec-07', E'Sobremesa sem culpa existe e cabe no protocolo, com moderacao.\n\nFrutas vermelhas, cacau acima de 70%, e receitas com castanhas satisfazem a vontade de doce sem o acucar refinado.\n\nExperimente: morangos com cacau amargo derretido e um toque de castanha.', 'https://www.youtube.com/watch?v=HvTFVsLT6p4'),
('rec-08', E'Bebidas funcionais ajudam na hidratacao e no ritual do dia sem acucar escondido.\n\nCha verde, agua aromatizada com limao e hortela, e sucos verdes equilibrados sao boas escolhas. Cuidado com sucos de fruta puros, que concentram acucar.\n\nExperimente: agua com gas, limao e folhas de hortela no lugar do refrigerante.', 'https://www.youtube.com/watch?v=EkwweVRYkoM'),
('rec-09', E'Marmitar e a estrategia mais poderosa para nao sair do plano na correria.\n\nCozinhe uma vez e monte porcoes para varios dias. Separe proteina, vegetais e uma gordura boa em potes prontos.\n\nExperimente: asse frango e legumes de uma vez e monte 4 marmitas equilibradas.', 'https://www.youtube.com/watch?v=_0oVPpvMZTY'),
('rec-10', E'Ovos sao o coringa do protocolo: baratos, versateis e muito nutritivos.\n\nMexidos, cozidos, pochê, omeletes ou frittatas com vegetais resolvem qualquer refeicao. Ricos em proteina, saciam por horas.\n\nExperimente: uma frittata de ovos com espinafre, tomate e azeite.', 'https://www.youtube.com/watch?v=3wv301z5KOc'),
('rec-11', E'Peixes e frutos do mar sao fontes de omega-3, uma gordura poderosamente anti-inflamatoria.\n\nSardinha, salmao e outros peixes preparados de forma simples (grelhados ou assados) sao rapidos e potentes.\n\nExperimente: sardinha grelhada com limao, azeite e uma salada verde.', 'https://www.youtube.com/watch?v=NkdTJpY6MyY'),
('rec-12', E'Vegetais podem ser a estrela do prato quando bem preparados.\n\nCouve-flor, abobrinha e brocolis assados no azeite com alho e ervas ganham sabor e textura. Fuja do cozido sem graca.\n\nExperimente: couve-flor assada no azeite com curcuma e alho.', 'https://www.youtube.com/watch?v=aOCap7ELDNs'),

-- ===== Mente e Mindfulness (mind) =====
('min-01', E'A fome emocional pede uma pausa, nao comida. Uma respiracao consciente cria o espaco para escolher.\n\nAntes de comer por impulso, respire fundo 3 vezes, bem devagar. Esse pequeno intervalo tira voce do piloto automatico e devolve o controle.\n\nPratica: da proxima vez que bater a vontade fora de hora, respire 3 vezes e beba um copo de agua antes de decidir.', 'https://www.youtube.com/watch?v=54YXuwPR50Q'),
('min-02', E'A gratidao muda a quimica do seu dia. Registrar o que ha de bom treina o cerebro para o que funciona.\n\nAnotar 3 gratidoes por dia reduz ansiedade e melhora a relacao com a comida e com o corpo.\n\nPratica: antes de dormir, escreva 3 coisas boas do seu dia, por menores que sejam.', 'https://www.youtube.com/watch?v=85uY4aO7SYE'),
('min-03', E'A meditacao do corpo leve relaxa a tensao acumulada e reconecta voce com o presente.\n\nSente-se confortavel, feche os olhos e leve a atencao para cada parte do corpo, soltando a tensao. Poucos minutos ja acalmam o sistema nervoso.\n\nPratica: reserve 10 minutos hoje para o audio guiado desta aula.', 'https://www.youtube.com/watch?v=pwaI2hCCSPw'),
('min-04', E'Dormir bem e tao importante quanto comer bem. A falta de sono aumenta a fome e a vontade de doces.\n\nCrie um ritual noturno: menos telas, luz baixa, um cha sem cafeina. O sono reparador acelera o emagrecimento e melhora o humor.\n\nPratica: desligue as telas 1 hora antes de dormir por 3 noites e observe a diferenca.', 'https://www.youtube.com/watch?v=9O9QU3FJrZA'),
('min-05', E'Recaida faz parte do processo. O que define o resultado nao e o deslize, e a proxima escolha.\n\nUm dia fora do plano nao apaga semanas de progresso. Volte ao ritmo na proxima refeicao, sem culpa e sem compensar com restricao extrema.\n\nPratica: depois de um deslize, escreva o gatilho que levou a ele e siga em frente.', 'https://www.youtube.com/watch?v=HZt6mGDZnpU'),
('min-06', E'Movimento nao e castigo, e celebracao do que o corpo pode fazer.\n\nEscolha uma atividade que voce gosta e comece pequeno: uma caminhada de 30 minutos ja muda o dia. A constancia vale mais que a intensidade.\n\nPratica: marque uma caminhada hoje e registre no seu Check-in Diario.', 'https://www.youtube.com/watch?v=RylLBe8yAwc'),
('min-07', E'Ninguem se transforma sozinho. Caminhar acompanhada acelera e sustenta a mudanca.\n\nCompartilhar a jornada, pedir apoio e celebrar pequenas vitorias com a comunidade aumenta muito a chance de sucesso.\n\nPratica: conte para alguem de confianca sobre a sua meta dos 45 dias.', 'https://www.youtube.com/watch?v=Glv257hNhpo'),
('min-08', E'A ultima etapa e ancorar a nova identidade: voce nao esta de dieta, voce se tornou uma pessoa que se cuida.\n\nRituais simples ajudam a consolidar quem voce se tornou. Celebre a borboleta e defina como vai manter o voo depois dos 45 dias.\n\nPratica: escreva uma carta para a sua versao de daqui a 6 meses.', 'https://www.youtube.com/watch?v=dZqAOIiVhL0')

) as v(slug, content, video)
where l.slug = v.slug;
